name: AWS Configuration

on:
  workflow_dispatch:

jobs:
  configure-aws-creds:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_INFRA_ROLE_ARN }}
          aws-region: us-east-1
